version: '3.0'
services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '49153:5432'
    volumes: 
      - data:/var/lib/postgresql/data
volumes:
  data:
    driver: local