version: '3.0'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=aled
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=watimotdepasse
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5434:5432'
    volumes: 
      - data:/var/lib/postgresql/data
volumes:
  data:
    driver: local